# NUMPY

In [ ]:
PYTHON LIST V/S NUMPY ARRAY
- can hold elements of different datatypes - must be of same type
- slower for numerical operations - much faster due to optimised c backend
- Consumes more memory - Uses less memory and is more efficient
- Limited build in operations - Have more operations to work on
- Limited support in scientific libraries - Wide support for scientific, visualisation, ML libraries

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
# number of elements
a.size

3

In [6]:
# size of each element - byte 8 - bits 64
a.itemsize

8

In [9]:
a = np.array([1,2,3], dtype='int32') # 32 bit

In [10]:
a.itemsize # byte

4

In [11]:
a = np.array([1,2,3], dtype='int16') # 16 bit

In [12]:
a.itemsize # byte

2

In [13]:
a = np.array([1,2,3], dtype='int8') # 8 bit

In [14]:
a.itemsize # byte

1

In [15]:
a = np.array([1,2,3, 1000], dtype='int8') # 8 bit

/var/folders/yv/_ddlvjkn6k11_jp7sl8jcy500000gn/T/ipykernel_47052/312744479.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1,2,3, 1000], dtype='int8') # 8 bit


In [16]:
a = np.array([1,2,3,200], dtype='int8') # 8 bit

/var/folders/yv/_ddlvjkn6k11_jp7sl8jcy500000gn/T/ipykernel_47052/3984844114.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1,2,3,200], dtype='int8') # 8 bit


In [17]:
a = np.array([1,2,3,120], dtype='int8') # 8 bit

In [19]:
# get datatype
a.dtype

dtype('int8')

In [21]:
# total size of array
a.nbytes

4

In [22]:
a.itemsize

1

In [26]:
# 2D arrays
b = np.array(
    [
        [1,2,3,4,5,6,7,8,9,10],
        [11,12,13,14,15,16,17,18,19,20],
    ]
)

In [27]:
b.dtype

dtype('int64')

In [28]:
b.itemsize

8

In [29]:
b.nbytes

160

In [30]:
# dimension
b.ndim

2

In [31]:
a.ndim

1

In [32]:
# shape
b.shape

(2, 10)

In [33]:
a.shape

(4,)

In [35]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [38]:
# get specific row
b[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
# get specific element
b[1][5]

16

In [41]:
# get specific column - startingIdx, lastInx (excluded), steps
b[ : , 4]

array([ 5, 15])

In [42]:
# get specific row
b[1, : ]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
b[1, 0:5 ]

array([11, 12, 13, 14, 15])

In [44]:
b[1, 0:5:2 ]

array([11, 13, 15])

In [45]:
b[1, 9]

20

In [46]:
# UPDATE AN ELEMENT
b[1, 9] = 200

In [47]:
b[1, 9]

200

In [48]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19, 200]])

In [49]:
# 3D arrays
c = np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9],
        ],
        [
            [11,12,13],
            [14,15,16],
            [17,18,19],
        ]
    ]
)

In [50]:
c[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
c[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [52]:
c[0][1][2]

6

In [55]:
# create zero array
np.zeros((4,5), dtype='int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [56]:
np.zeros((4,), dtype='int32')

array([0, 0, 0, 0], dtype=int32)

In [57]:
np.zeros((4,5,2), dtype='int32')

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int32)

In [58]:
np.ones((4,5), dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [59]:
np.full((4,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [62]:
# random array
np.random.rand(3,4)

array([[0.59909941, 0.77314015, 0.11525419, 0.04641616],
       [0.99126881, 0.00285285, 0.25404313, 0.05944875],
       [0.76462583, 0.50247762, 0.9145559 , 0.557238  ]])

In [63]:
np.random.rand(3,4) * 100

array([[ 6.62715389, 11.4912978 , 25.46782764, 90.47082205],
       [53.83955523, 31.6601024 ,  1.72260961, 83.40637438],
       [55.96588712,  4.205393  , 20.26239921, 47.92926417]])

In [67]:
np.random.randint(1,100, size=(3,4))

array([[ 8, 29, 86,  9],
       [13, 43, 58, 44],
       [99, 16, 22, 80]])

In [72]:
# INDENTITY MATRIX
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
# deep and shallow copy

In [74]:
p = np.array([1,2,3,4,5])

In [76]:
q = p # shallow copy

In [77]:
q = p.copy() # deep copy

In [78]:
q[0]

1

In [79]:
p[0]

1

In [80]:
q[0] = 10

In [81]:
p[0]

1

In [82]:
q[0]

10

In [83]:
p

array([1, 2, 3, 4, 5])

In [84]:
# some mathemetic

In [85]:
p + 10

array([11, 12, 13, 14, 15])

In [86]:
p - 10

array([-9, -8, -7, -6, -5])

In [87]:
p * 10

array([10, 20, 30, 40, 50])

In [88]:
p / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [89]:
q

array([10,  2,  3,  4,  5])

In [90]:
q + p

array([11,  4,  6,  8, 10])

In [91]:
np.max(p)

5

In [92]:
np.min(p)

1

In [93]:
np.sum(p)

15

In [94]:
np.average(p)

3.0

In [95]:
np.mean(p)

3.0